In [6]:
import torch.nn as nn
import numpy as np
import torch

In [7]:
#Training and testing data
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]], dtype = 'float32')
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]], dtype = 'float32')

In [8]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [9]:
from torch.utils.data import TensorDataset

In [10]:
#Define Dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [11]:
from torch.utils.data import DataLoader

In [12]:
batch_size = 5
train_d1 = DataLoader(train_ds, batch_size, shuffle= True)

In [13]:
for xb, yb in train_d1:
  print(xb)
  print(yb)
  break

tensor([[ 74.,  66.,  43.],
        [ 68.,  97.,  70.],
        [ 73.,  66.,  44.],
        [102.,  43.,  37.],
        [101.,  44.,  37.]])
tensor([[ 57.,  69.],
        [102., 120.],
        [ 57.,  69.],
        [ 22.,  37.],
        [ 21.,  38.]])


In [14]:
#nn.Linear
#Define Model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3711,  0.5445,  0.3492],
        [-0.1375, -0.0965, -0.2557]], requires_grad=True)
Parameter containing:
tensor([0.4163, 0.4058], requires_grad=True)


In [15]:
#Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.3711,  0.5445,  0.3492],
         [-0.1375, -0.0965, -0.2557]], requires_grad=True),
 Parameter containing:
 tensor([0.4163, 0.4058], requires_grad=True)]

In [16]:
#Generate Predictions
preds = model(inputs)
preds

tensor([[ 24.8285, -27.0938],
        [ 36.9181, -36.9660],
        [ 61.3550, -39.3224],
        [ -1.0960, -27.2286],
        [ 51.5329, -36.2487],
        [ 23.9129, -27.1347],
        [ 36.7228, -37.1252],
        [ 61.3331, -39.7156],
        [ -0.1805, -27.1877],
        [ 52.2532, -36.3670],
        [ 24.6332, -27.2530],
        [ 36.0025, -37.0069],
        [ 61.5503, -39.1632],
        [ -1.8163, -27.1103],
        [ 52.4485, -36.2077]], grad_fn=<AddmmBackward>)

In [18]:
#Loss function
import torch.nn.functional as F

In [19]:
#Define loss function
loss_fn = F.mse_loss

In [20]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(9573.8184, grad_fn=<MseLossBackward>)


In [21]:
#Optimizer
opt = torch.optim.SGD(model.parameters(), lr= 1e-5)

In [27]:
#Train the model
#Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_d1):
  
  #Repeat for given no of epochs
  for epoch in range(num_epochs):
    
    #Train with batches of data
    for xb, yb in train_d1:
      
      #generate prediction
      pred = model(xb)

      #Calculate loss
      loss = loss_fn(pred, yb)

      #Compute Gradients
      loss.backward()

      #Update parameters using gradients
      opt.step()

      #Reset the gradients to zero
      opt.zero_grad()

      #Print the progress
      if(epoch+1) % 10 == 0:
        print('epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [28]:
fit(100, model, loss_fn, opt, train_d1)

epoch [10/100], Loss: 63.8472
epoch [10/100], Loss: 142.7022
epoch [10/100], Loss: 333.9593
epoch [20/100], Loss: 91.1582
epoch [20/100], Loss: 84.6571
epoch [20/100], Loss: 215.0591
epoch [30/100], Loss: 37.3962
epoch [30/100], Loss: 92.8133
epoch [30/100], Loss: 153.2821
epoch [40/100], Loss: 47.7341
epoch [40/100], Loss: 107.7182
epoch [40/100], Loss: 64.0513
epoch [50/100], Loss: 107.6199
epoch [50/100], Loss: 5.4055
epoch [50/100], Loss: 58.6785
epoch [60/100], Loss: 27.1773
epoch [60/100], Loss: 66.9879
epoch [60/100], Loss: 38.5349
epoch [70/100], Loss: 35.1636
epoch [70/100], Loss: 48.2630
epoch [70/100], Loss: 23.3704
epoch [80/100], Loss: 44.1081
epoch [80/100], Loss: 4.9098
epoch [80/100], Loss: 40.8539
epoch [90/100], Loss: 15.5088
epoch [90/100], Loss: 26.7062
epoch [90/100], Loss: 36.4822
epoch [100/100], Loss: 10.2538
epoch [100/100], Loss: 31.2642
epoch [100/100], Loss: 26.9850


In [29]:
#Generate Prediction
preds = model(inputs)
preds

tensor([[ 57.4193,  71.7502],
        [ 81.0825,  97.2758],
        [119.6010, 137.9718],
        [ 23.0081,  44.8635],
        [ 99.0122, 108.7620],
        [ 56.1941,  70.7391],
        [ 80.7497,  96.7158],
        [119.7999, 138.2502],
        [ 24.2333,  45.8746],
        [ 99.9046, 109.2130],
        [ 57.0865,  71.1902],
        [ 79.8573,  96.2647],
        [119.9338, 138.5318],
        [ 22.1157,  44.4124],
        [100.2373, 109.7731]], grad_fn=<AddmmBackward>)

In [30]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [31]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.7579, 68.2432]], grad_fn=<AddmmBackward>)